[package]
name = "my-opendatastructure-rs"
version = "0.1.0"
authors = ["Koji Ota <afterjnih@gmail.com>"]
edition = "2018"

[dependencies]

[dev-dependencies]
rand = "0.6"
getopts = "0.2"
criterion = "0.2"

[[bench]]
name = "my_benchmark"
harness = false
